/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Presentacion;

/**
 *
 * @author Synd
 */
public class Actualizar_monto extends javax.swing.JFrame {

    /**
     * Creates new form Actualizar_monto
     */
    public Actualizar_monto() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JLB_Actualizar = new javax.swing.JLabel();
        JBTN_Atras_config = new javax.swing.JButton();
        JTX_monto = new javax.swing.JTextField();
        JTX_INGRESAR = new javax.swing.JTextField();
        JLB_sport_icon = new javax.swing.JLabel();
        JLB_Ingresar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snacks_Bums.com");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        JLB_Actualizar.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        JLB_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        JLB_Actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLB_Actualizar.setText("Actualizar");

        JBTN_Atras_config.setBackground(new java.awt.Color(102, 102, 255));
        JBTN_Atras_config.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        JBTN_Atras_config.setForeground(new java.awt.Color(255, 255, 255));
        JBTN_Atras_config.setText("Atras");
        JBTN_Atras_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_Atras_configActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(JLB_Actualizar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBTN_Atras_config)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLB_Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(JBTN_Atras_config)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 500));
        jPanel1.add(JTX_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 220, 30));
        jPanel1.add(JTX_INGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 220, 30));

        JLB_sport_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLB_sport_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sport (1).png"))); // NOI18N
        jPanel1.add(JLB_sport_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 260, 260));

        JLB_Ingresar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        JLB_Ingresar.setText("Ingresar");
        JLB_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(JLB_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 30));

        jLabel4.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Monto");
        jLabel4.setToolTipText("");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN_Atras_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_Atras_configActionPerformed
        new config().setVisible(true);
        this.dispose();




        // TODO add your handling code here:
    }//GEN-LAST:event_JBTN_Atras_configActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_monto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_monto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_monto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_monto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actualizar_monto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_Atras_config;
    private javax.swing.JLabel JLB_Actualizar;
    private javax.swing.JLabel JLB_Ingresar;
    private javax.swing.JLabel JLB_sport_icon;
    private javax.swing.JTextField JTX_INGRESAR;
    private javax.swing.JTextField JTX_monto;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
