/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Presentacion;

/**
 *
 * @author Synd
 */
public class cambio_pass extends javax.swing.JFrame {

    /**
     * Creates new form cambio_pass
     */
    public cambio_pass() {
        initComponents();
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JBTN_RETURN_CONFIG = new javax.swing.JButton();
        JTX_Ingrese_antigua_contra = new javax.swing.JTextField();
        JTX_Enter_new_pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JLB_Ingrese_pass = new javax.swing.JLabel();
        JLB_ingrese_new_pass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Snacks_Bums.com");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cambio de contraseña");

        JBTN_RETURN_CONFIG.setBackground(new java.awt.Color(102, 102, 255));
        JBTN_RETURN_CONFIG.setFont(new java.awt.Font("Gadugi", 3, 14)); // NOI18N
        JBTN_RETURN_CONFIG.setForeground(new java.awt.Color(255, 255, 255));
        JBTN_RETURN_CONFIG.setText("Atras");
        JBTN_RETURN_CONFIG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTN_RETURN_CONFIGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBTN_RETURN_CONFIG)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(JBTN_RETURN_CONFIG)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 500));
        jPanel1.add(JTX_Ingrese_antigua_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 192, 210, 30));
        jPanel1.add(JTX_Enter_new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 210, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sport (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 270, -1));

        JLB_Ingrese_pass.setFont(new java.awt.Font("Gadugi", 3, 12)); // NOI18N
        JLB_Ingrese_pass.setText("Ingrese su contra..");
        jPanel1.add(JLB_Ingrese_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 140, 30));

        JLB_ingrese_new_pass.setFont(new java.awt.Font("Gadugi", 3, 12)); // NOI18N
        JLB_ingrese_new_pass.setText("Ingrese nueva contra..");
        jPanel1.add(JLB_ingrese_new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 140, 30));

        jLabel3.setBackground(new java.awt.Color(102, 153, 255));
        jLabel3.setFont(new java.awt.Font("Gadugi", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"Sin esfuerzo no hay gloria\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 340, 30));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBTN_RETURN_CONFIGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTN_RETURN_CONFIGActionPerformed
        new config().setVisible(true);
        this.dispose();




        // TODO add your handling code here:
    }//GEN-LAST:event_JBTN_RETURN_CONFIGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cambio_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cambio_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cambio_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cambio_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cambio_pass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTN_RETURN_CONFIG;
    private javax.swing.JLabel JLB_Ingrese_pass;
    private javax.swing.JLabel JLB_ingrese_new_pass;
    private javax.swing.JTextField JTX_Enter_new_pass;
    private javax.swing.JTextField JTX_Ingrese_antigua_contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
